import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";
import { ensurePlatformDirectories, resolvePlatformDirectories } from "./host-profile.ts";

/** Durable host-local job ledger; bytes and credentials never enter this DB. */
export const JOB_PROTOCOL_VERSION = 1 as const;
export type JobState = "queued" | "waiting_approval" | "running" | "paused" | "succeeded" | "failed" | "cancelled" | "interrupted";
export type RestartPolicy = "resume" | "retry_from_checkpoint" | "restart" | "none";
export type Resources = { network?: boolean; diskBytes?: number; cpuSlots?: number; gpu?: "exclusive"; workspace?: boolean };
export type ArtifactRef = { id: string; digest?: string };
export type Job = { protocolVersion: 1; id: string; kind: string; requestedBy: string; capabilityScope: string[]; state: JobState; resources: Resources; restartPolicy: RestartPolicy; progress: { phase: string; completed: number; total?: number; updatedAt: number }; checkpoint?: unknown; inputs: ArtifactRef[]; outputs: ArtifactRef[]; retentionClass: string; createdAt: number; updatedAt: number; startedAt?: number; finishedAt?: number; cancelRequestedAt?: number; error?: { code: string; message: string; retryable: boolean } };
export type CreateJob = Omit<Job, "protocolVersion" | "state" | "progress" | "outputs" | "createdAt" | "updatedAt"> & { progress?: { phase: string; completed: number; total?: number }; outputs?: ArtifactRef[] };
type Row = Record<string, unknown>;
const end = new Set<JobState>(["succeeded", "failed", "cancelled", "interrupted"]);
const parse = <T>(v: unknown, fallback: T): T => { try { return JSON.parse(String(v)) as T; } catch { return fallback; } };
const checkPositive = (v: number | undefined, name: string) => { if (v !== undefined && (!Number.isSafeInteger(v) || v <= 0)) throw new Error(`${name} must be a positive integer`); };

export class JobRepository {
  private db: DatabaseSync; private clock: () => number; private disk?: number; private cpu: number;
  constructor(options: { databasePath: string; diskCapacityBytes?: number; cpuSlots?: number; now?: () => number }) {
    if (!path.isAbsolute(options.databasePath)) throw new Error("job databasePath must be absolute");
    checkPositive(options.diskCapacityBytes, "diskCapacityBytes"); checkPositive(options.cpuSlots, "cpuSlots");
    fs.mkdirSync(path.dirname(options.databasePath), { recursive: true, mode: 0o700 });
    this.db = new DatabaseSync(options.databasePath, { timeout: 5_000 }); this.clock = options.now ?? Date.now; this.disk = options.diskCapacityBytes; this.cpu = options.cpuSlots ?? 1;
    this.db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;
      CREATE TABLE IF NOT EXISTS jobs (id TEXT PRIMARY KEY,kind TEXT NOT NULL,requested_by TEXT NOT NULL,scope TEXT NOT NULL,state TEXT NOT NULL,resources TEXT NOT NULL,restart TEXT NOT NULL,progress TEXT NOT NULL,checkpoint TEXT,inputs TEXT NOT NULL,outputs TEXT NOT NULL,retention TEXT NOT NULL,created INTEGER NOT NULL,updated INTEGER NOT NULL,started INTEGER,finished INTEGER,cancel_requested INTEGER,error TEXT);
      CREATE TABLE IF NOT EXISTS job_events (job_id TEXT NOT NULL,seq INTEGER NOT NULL,at INTEGER NOT NULL,type TEXT NOT NULL,detail TEXT,PRIMARY KEY(job_id,seq),FOREIGN KEY(job_id) REFERENCES jobs(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS job_leases (job_id TEXT NOT NULL,resource TEXT NOT NULL,quantity INTEGER NOT NULL,PRIMARY KEY(job_id,resource),FOREIGN KEY(job_id) REFERENCES jobs(id) ON DELETE CASCADE);
      CREATE INDEX IF NOT EXISTS idx_jobs_state ON jobs(state,updated DESC);`);
  }
  private tx<T>(fn: () => T): T { this.db.exec("BEGIN IMMEDIATE"); try { const x = fn(); this.db.exec("COMMIT"); return x; } catch (e) { this.db.exec("ROLLBACK"); throw e; } }
  private row(id: string): Row | null { return this.db.prepare("SELECT * FROM jobs WHERE id=?").get(id) ?? null; }
  private asJob(r: Row): Job { return { protocolVersion: 1, id: String(r.id), kind: String(r.kind), requestedBy: String(r.requested_by), capabilityScope: parse(r.scope, []), state: r.state as JobState, resources: parse(r.resources, {}), restartPolicy: r.restart as RestartPolicy, progress: parse(r.progress, { phase: "queued", completed: 0, updatedAt: Number(r.updated) }), checkpoint: r.checkpoint ? parse(r.checkpoint, undefined) : undefined, inputs: parse(r.inputs, []), outputs: parse(r.outputs, []), retentionClass: String(r.retention), createdAt: Number(r.created), updatedAt: Number(r.updated), startedAt: r.started ? Number(r.started) : undefined, finishedAt: r.finished ? Number(r.finished) : undefined, cancelRequestedAt: r.cancel_requested ? Number(r.cancel_requested) : undefined, error: r.error ? parse(r.error, undefined) : undefined }; }
  get(id: string): Job | null { const r = this.row(id); return r ? this.asJob(r) : null; }
  list(limit = 100): Job[] { return this.db.prepare("SELECT * FROM jobs ORDER BY created DESC LIMIT ?").all(Math.max(1, Math.min(500, Math.floor(limit)))).map((r) => this.asJob(r)); }
  events(id: string) { return this.db.prepare("SELECT * FROM job_events WHERE job_id=? ORDER BY seq").all(id).map((r) => ({ seq: Number(r.seq), at: Number(r.at), type: String(r.type), detail: r.detail ? parse(r.detail, undefined) : undefined })); }
  private event(id: string, type: string, detail?: unknown) { const seq = Number(this.db.prepare("SELECT COALESCE(MAX(seq),0)+1 AS n FROM job_events WHERE job_id=?").get(id)?.n ?? 1); this.db.prepare("INSERT INTO job_events VALUES (?,?,?,?,?)").run(id, seq, this.clock(), type, detail === undefined ? null : JSON.stringify(detail)); }
  create(input: CreateJob): Job {
    if (!/^[a-z][a-z0-9._-]{0,127}$/i.test(input.kind) || !input.requestedBy.trim()) throw new Error("job kind and requestedBy are required");
    if (!/^[a-z0-9][a-z0-9._:-]{0,127}$/i.test(input.id)) throw new Error("job id must be an identifier");
    if (!(["resume", "retry_from_checkpoint", "restart", "none"] as string[]).includes(input.restartPolicy)) throw new Error("invalid restart policy");
    checkPositive(input.resources.diskBytes, "diskBytes"); checkPositive(input.resources.cpuSlots, "cpuSlots"); if (input.resources.gpu && input.resources.gpu !== "exclusive") throw new Error("gpu must be exclusive");
    const now = this.clock(), p = { phase: input.progress?.phase ?? "queued", completed: input.progress?.completed ?? 0, ...(input.progress?.total === undefined ? {} : { total: input.progress.total }), updatedAt: now };
    if (!Number.isFinite(p.completed) || p.completed < 0 || (p.total !== undefined && p.total < p.completed)) throw new Error("invalid progress");
    this.tx(() => { this.db.prepare("INSERT INTO jobs (id,kind,requested_by,scope,state,resources,restart,progress,checkpoint,inputs,outputs,retention,created,updated) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(input.id,input.kind,input.requestedBy,JSON.stringify([...new Set(input.capabilityScope)]),"queued",JSON.stringify(input.resources),input.restartPolicy,JSON.stringify(p),input.checkpoint === undefined ? null : JSON.stringify(input.checkpoint),JSON.stringify(input.inputs),JSON.stringify(input.outputs ?? []),input.retentionClass || "default",now,now); this.event(input.id,"created",{ resources: input.resources, restartPolicy: input.restartPolicy }); }); return this.get(input.id)!;
  }
  private unavailable(j: Job): "gpu_busy" | "cpu_busy" | "disk_insufficient" | null { if (j.resources.gpu === "exclusive" && Number(this.db.prepare("SELECT COUNT(*) n FROM job_leases WHERE resource='gpu'").get()?.n ?? 0)) return "gpu_busy"; if (j.resources.cpuSlots && Number(this.db.prepare("SELECT COALESCE(SUM(quantity),0) n FROM job_leases WHERE resource='cpu'").get()?.n ?? 0) + j.resources.cpuSlots > this.cpu) return "cpu_busy"; if (j.resources.diskBytes && this.disk !== undefined && Number(this.db.prepare("SELECT COALESCE(SUM(quantity),0) n FROM job_leases WHERE resource='disk'").get()?.n ?? 0) + j.resources.diskBytes > this.disk) return "disk_insufficient"; return null; }
  private lease(j: Job) { if (j.resources.gpu) this.db.prepare("INSERT INTO job_leases VALUES (?,'gpu',1)").run(j.id); if (j.resources.cpuSlots) this.db.prepare("INSERT INTO job_leases VALUES (?,'cpu',?)").run(j.id,j.resources.cpuSlots); if (j.resources.diskBytes) this.db.prepare("INSERT INTO job_leases VALUES (?,'disk',?)").run(j.id,j.resources.diskBytes); }
  private release(id: string) { this.db.prepare("DELETE FROM job_leases WHERE job_id=?").run(id); }
  start(id: string): { started: true; job: Job } | { started: false; reason: "not_runnable" | "gpu_busy" | "cpu_busy" | "disk_insufficient" } { return this.tx(() => { const j = this.get(id); if (!j || j.state !== "queued") return { started: false as const, reason: "not_runnable" as const }; const reason = this.unavailable(j); if (reason) { this.event(id,"start_deferred",{ reason }); return { started: false as const, reason }; } const now = this.clock(); this.lease(j); this.db.prepare("UPDATE jobs SET state='running',started=COALESCE(started,?),updated=?,error=NULL WHERE id=?").run(now,now,id); this.event(id,"started"); return { started: true as const, job: this.get(id)! }; }); }
  checkpoint(id: string, checkpoint: unknown, progress: { phase: string; completed: number; total?: number }): Job { return this.tx(() => { const j = this.get(id); if (!j || j.state !== "running") throw new Error("only running jobs checkpoint"); if (progress.completed < j.progress.completed || progress.completed < 0 || (progress.total !== undefined && progress.total < progress.completed)) throw new Error("checkpoint cannot move backwards"); const p = { ...progress, updatedAt: this.clock() }; this.db.prepare("UPDATE jobs SET checkpoint=?,progress=?,updated=? WHERE id=?").run(JSON.stringify(checkpoint),JSON.stringify(p),p.updatedAt,id); this.event(id,"checkpoint",progress); return this.get(id)!; }); }
  requestCancel(id: string): Job | null { return this.tx(() => { const j = this.get(id); if (!j || end.has(j.state)) return j; const now = this.clock(); if (j.state === "queued" || j.state === "paused" || j.state === "waiting_approval") { this.db.prepare("UPDATE jobs SET state='cancelled',finished=?,updated=?,cancel_requested=? WHERE id=?").run(now,now,now,id); this.release(id); this.event(id,"cancelled_before_start"); } else { this.db.prepare("UPDATE jobs SET cancel_requested=?,updated=? WHERE id=?").run(now,now,id); this.event(id,"cancel_requested"); } return this.get(id); }); }
  cancelSettled(id: string): Job { return this.tx(() => { const j = this.get(id); if (!j || j.state !== "running") throw new Error("only running jobs can settle cancellation"); const now=this.clock(); this.db.prepare("UPDATE jobs SET state='cancelled',finished=?,updated=? WHERE id=?").run(now,now,id); this.release(id); this.event(id,"cancelled"); return this.get(id)!; }); }
  succeed(id: string, outputs: ArtifactRef[]): Job { if (!outputs.length || outputs.some((x) => !x.id || !x.digest)) throw new Error("success requires verified output digests"); return this.tx(() => { const j=this.get(id); if (!j || j.state !== "running" || j.cancelRequestedAt) throw new Error("only uncancelled running jobs can succeed"); const now=this.clock(), p={ ...j.progress, phase:"verified", ...(j.progress.total === undefined ? {} : { completed:j.progress.total }), updatedAt:now }; this.db.prepare("UPDATE jobs SET state='succeeded',outputs=?,progress=?,finished=?,updated=? WHERE id=?").run(JSON.stringify(outputs),JSON.stringify(p),now,now,id); this.release(id); this.event(id,"succeeded",{ outputs:outputs.map((x)=>x.id) }); return this.get(id)!; }); }
  fail(id: string, error: { code: string; message: string; retryable: boolean }): Job { if (!error.code || !error.message) throw new Error("structured error required"); return this.tx(() => { const j=this.get(id); if (!j || end.has(j.state)) throw new Error("only active job can fail"); const now=this.clock(); this.db.prepare("UPDATE jobs SET state='failed',error=?,finished=?,updated=? WHERE id=?").run(JSON.stringify(error),now,now,id); this.release(id); this.event(id,"failed",{ code:error.code }); return this.get(id)!; }); }
  recover(kind?: string): { queued: string[]; interrupted: string[] } { return this.tx(() => { const queued:string[]=[],interrupted:string[]=[], rows = kind ? this.db.prepare("SELECT * FROM jobs WHERE kind=? AND state IN ('running','paused','waiting_approval')").all(kind) : this.db.prepare("SELECT * FROM jobs WHERE state IN ('running','paused','waiting_approval')").all(); for (const row of rows) { const j=this.asJob(row), now=this.clock(); this.release(j.id); if (j.restartPolicy === "none") { const modelDownload = j.kind === "model.download"; this.db.prepare("UPDATE jobs SET state='interrupted',finished=?,updated=?,error=? WHERE id=?").run(now,now,JSON.stringify({ code:"host_restarted",message:modelDownload ? "host restarted; restart this download to obtain a fresh verified transfer" : "host restarted; this job does not support recovery",retryable:modelDownload }),j.id); interrupted.push(j.id); this.event(j.id,"recovered_interrupted"); } else { const cp=j.restartPolicy === "restart" ? null : row.checkpoint; this.db.prepare("UPDATE jobs SET state='queued',checkpoint=?,updated=?,started=NULL,cancel_requested=NULL WHERE id=?").run(cp,now,j.id); queued.push(j.id); this.event(j.id,"recovered_queued",{ policy:j.restartPolicy,checkpointRetained:cp!==null }); } } return { queued,interrupted }; }); }
}

/** Deterministic fixture for adapter conformance and recovery/cancel tests. */
export function runFakeCheckpointableJob(repo: JobRepository, id: string, steps: number, onStep?: (step: number) => void): Job { if (!Number.isSafeInteger(steps) || steps < 1) throw new Error("steps must be positive"); const started=repo.start(id); if (!started.started) throw new Error(`job did not start: ${started.reason}`); for (let n=1;n<=steps;n++) { onStep?.(n); if (repo.get(id)!.cancelRequestedAt) return repo.cancelSettled(id); repo.checkpoint(id,{ completedSteps:n },{ phase:"work",completed:n,total:steps }); } return repo.succeed(id,[{ id:`fake-output:${id}`,digest:crypto.createHash("sha256").update(id).digest("hex") }]); }

type GlobalJobs = typeof globalThis & { __lal_jobs?: JobRepository };
export function getJobRepository(): JobRepository { const g=globalThis as GlobalJobs; if (!g.__lal_jobs) { const dirs=ensurePlatformDirectories(resolvePlatformDirectories()); g.__lal_jobs=new JobRepository({ databasePath:path.join(dirs.state,"jobs.sqlite") }); } return g.__lal_jobs; }
