/**
 * Durable lineage and evaluation evidence. This records immutable facts from
 * the registry/jobs layers but never loads a model or runs a benchmark.
 */
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";
import { ensurePlatformDirectories, resolvePlatformDirectories } from "./host-profile.ts";

export const LINEAGE_EVALUATION_SCHEMA_VERSION = 1 as const;
export type LineageKind = "model" | "dataset" | "adapter" | "artifact" | "conversation" | "run";
export type LineageEntity = { id: string; kind: LineageKind; digest?: string; metadata: Record<string, unknown>; retentionClass: string; recordedAt: number };
export type LineageRelation = { id: string; fromId: string; toId: string; relation: "derived_from" | "trained_on" | "evaluated_by" | "generated_by" | "used_by"; activityId?: string; recordedAt: number };
export type DatasetManifestInput = { sourceArtifactIds: string[]; rowIds: string[]; byteSha256: string; schemaVersion: string; license: string; intendedRole: string; limitations?: string; transformations: { name: string; version: string; inputSha256?: string }[] };
export type DatasetManifest = DatasetManifestInput & { id: `dataset:sha256:${string}`; rowCount: number; recordedAt: number };

export type EvaluationCaseInput = { name: string; promptTemplateSha256: string; datasetRevision: string; expected?: Record<string, unknown>; tags?: string[] };
export type EvaluationCase = EvaluationCaseInput & { id: `case:sha256:${string}` };
export type EvaluationSuiteInput = { name: string; version: string; datasetId: string; datasetRevision: string; datasetSha256: string; license: string; scorer: { id: string; revision: string }; contaminationNotes?: string; split: "smoke" | "held_out" | "development"; seeds: number[]; repeats: number; warmup: { runs: number; discard: number }; capabilityDomain: string; minimumRuntime: Record<string, unknown>; cases: EvaluationCaseInput[] };
export type EvaluationSuite = Omit<EvaluationSuiteInput, "cases"> & { id: `suite:sha256:${string}`; cases: EvaluationCase[]; createdAt: number };
export type EvaluationRunInput = { id: string; suiteId: string; artifactId: string; runtimeId: string; chatTemplateSha256: string; hostFingerprintSha256: string; softwareRevision: string; environmentRevision: string; decoding: Record<string, unknown>; seed: number; repeat: number };
export type EvaluationCaseResult = { caseId: string; outcome: "pass" | "fail" | "error"; rawOutput: string; scorerOutput: Record<string, unknown>; metrics?: Record<string, number>; error?: { code: string; message: string } };
export type EvaluationRun = EvaluationRunInput & { protocolVersion: typeof LINEAGE_EVALUATION_SCHEMA_VERSION; state: "running" | "completed" | "failed"; startedAt: number; completedAt?: number; results: EvaluationCaseResult[]; summary?: { total: number; passed: number; failed: number; errors: number; passRate: number; meanLatencyMs?: number }; error?: { code: string; message: string } };
export type RunComparison = { runs: { id: string; suiteId: string; artifactId: string; runtimeId: string; state: EvaluationRun["state"]; summary?: EvaluationRun["summary"] }[]; caseOutcomes: Record<string, Record<string, EvaluationCaseResult["outcome"]>> };

const identifier = /^[a-z][a-z0-9._:-]{0,255}$/i;
const sha256 = /^[a-f0-9]{64}$/i;
const canonical = (value: unknown): string => Array.isArray(value) ? `[${value.map(canonical).join(",")}]` : value && typeof value === "object" ? `{${Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${canonical(item)}`).join(",")}}` : JSON.stringify(value);
const digest = (value: unknown) => crypto.createHash("sha256").update(canonical(value)).digest("hex");
const json = <T>(value: string | null, fallback: T): T => { try { return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } };
function assertId(value: string, subject: string) { if (!identifier.test(value)) throw new Error(`${subject} must be a stable identifier`); }
function assertHash(value: string, subject: string) { if (!sha256.test(value)) throw new Error(`${subject} must be a SHA-256 digest`); }
function noDuplicate<T>(values: T[], key: (value: T) => string, subject: string) { if (new Set(values.map(key)).size !== values.length) throw new Error(`${subject} contains duplicates`); }
function resultSummary(results: EvaluationCaseResult[]): NonNullable<EvaluationRun["summary"]> { const passed=results.filter((result)=>result.outcome==="pass").length, failed=results.filter((result)=>result.outcome==="fail").length, errors=results.filter((result)=>result.outcome==="error").length, latencies=results.flatMap((result)=>typeof result.metrics?.latencyMs==="number"?[result.metrics.latencyMs]:[]); return { total:results.length,passed,failed,errors,passRate:results.length ? passed/results.length : 0,...(latencies.length ? { meanLatencyMs:latencies.reduce((total,value)=>total+value,0)/latencies.length } : {}) }; }
function runInputFrom(run: EvaluationRun): EvaluationRunInput { const { protocolVersion: _protocolVersion,state: _state,startedAt: _startedAt,completedAt: _completedAt,results: _results,summary: _summary,error: _error,...input }=run; return input; }

export class LineageEvaluationRepository {
  private readonly db: DatabaseSync; private readonly now: () => number;
  constructor(options: { databasePath: string; now?: () => number }) {
    if (!path.isAbsolute(options.databasePath)) throw new Error("lineage databasePath must be absolute");
    fs.mkdirSync(path.dirname(options.databasePath), { recursive: true, mode: 0o700 }); this.db = new DatabaseSync(options.databasePath, { timeout: 5_000 }); this.now = options.now ?? Date.now;
    this.db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;
      CREATE TABLE IF NOT EXISTS lineage_entities (id TEXT PRIMARY KEY, kind TEXT NOT NULL, digest TEXT, metadata TEXT NOT NULL, retention TEXT NOT NULL, recorded INTEGER NOT NULL);
      CREATE TABLE IF NOT EXISTS lineage_relations (id TEXT PRIMARY KEY, from_id TEXT NOT NULL, to_id TEXT NOT NULL, relation TEXT NOT NULL, activity_id TEXT, recorded INTEGER NOT NULL, UNIQUE(from_id,to_id,relation,activity_id), FOREIGN KEY(from_id) REFERENCES lineage_entities(id), FOREIGN KEY(to_id) REFERENCES lineage_entities(id));
      CREATE TABLE IF NOT EXISTS dataset_manifests (id TEXT PRIMARY KEY, body TEXT NOT NULL, recorded INTEGER NOT NULL, FOREIGN KEY(id) REFERENCES lineage_entities(id));
      CREATE TABLE IF NOT EXISTS evaluation_suites (id TEXT PRIMARY KEY, body TEXT NOT NULL, created INTEGER NOT NULL);
      CREATE TABLE IF NOT EXISTS evaluation_cases (suite_id TEXT NOT NULL, id TEXT NOT NULL, body TEXT NOT NULL, PRIMARY KEY(suite_id,id), FOREIGN KEY(suite_id) REFERENCES evaluation_suites(id) ON DELETE RESTRICT);
      CREATE TABLE IF NOT EXISTS evaluation_runs (id TEXT PRIMARY KEY, suite_id TEXT NOT NULL, body TEXT NOT NULL, state TEXT NOT NULL, started INTEGER NOT NULL, completed INTEGER, error TEXT, FOREIGN KEY(suite_id) REFERENCES evaluation_suites(id));
      CREATE TABLE IF NOT EXISTS evaluation_results (run_id TEXT NOT NULL, case_id TEXT NOT NULL, body TEXT NOT NULL, PRIMARY KEY(run_id,case_id), FOREIGN KEY(run_id) REFERENCES evaluation_runs(id) ON DELETE RESTRICT);`);
  }
  private transaction<T>(fn: () => T): T { this.db.exec("BEGIN IMMEDIATE"); try { const value=fn(); this.db.exec("COMMIT"); return value; } catch (error) { this.db.exec("ROLLBACK"); throw error; } }
  private entity(row: Record<string, unknown>): LineageEntity { return { id:String(row.id),kind:row.kind as LineageKind,...(row.digest ? { digest:String(row.digest) } : {}),metadata:json(String(row.metadata),{}),retentionClass:String(row.retention),recordedAt:Number(row.recorded) }; }
  private suite(row: Record<string, unknown>): EvaluationSuite { return { ...json(String(row.body),{}) as Omit<EvaluationSuite,"createdAt">,createdAt:Number(row.created) }; }
  private run(row: Record<string, unknown>): EvaluationRun { const body=json(String(row.body),{}) as EvaluationRunInput; const results=this.db.prepare("SELECT body FROM evaluation_results WHERE run_id=? ORDER BY case_id").all(String(row.id)).map((result)=>json(String(result.body),{}) as EvaluationCaseResult); return { ...body,protocolVersion:LINEAGE_EVALUATION_SCHEMA_VERSION,state:row.state as EvaluationRun["state"],startedAt:Number(row.started),...(row.completed ? { completedAt:Number(row.completed) } : {}),results,...(row.error ? { error:json(String(row.error),{ code:"unknown",message:"unknown" }) } : {}),...(row.state === "completed" ? { summary:resultSummary(results) } : {}) }; }

  recordEntity(input: Omit<LineageEntity,"recordedAt">): LineageEntity {
    assertId(input.id,"entity id"); if (input.digest) assertHash(input.digest,"entity digest"); if (!input.retentionClass.trim()) throw new Error("retentionClass is required");
    return this.transaction(()=>{ const existing=this.db.prepare("SELECT * FROM lineage_entities WHERE id=?").get(input.id) as Record<string,unknown>|undefined; const candidate={ ...input,digest:input.digest ?? null,metadata:input.metadata }; if (existing) { const old={ id:String(existing.id),kind:String(existing.kind),digest:existing.digest ? String(existing.digest) : null,metadata:json(String(existing.metadata),{}),retentionClass:String(existing.retention) }; if (canonical(old)!==canonical(candidate)) throw new Error(`immutable lineage entity conflict: ${input.id}`); return this.entity(existing); } const at=this.now(); this.db.prepare("INSERT INTO lineage_entities VALUES (?,?,?,?,?,?)").run(input.id,input.kind,input.digest ?? null,JSON.stringify(input.metadata),input.retentionClass,at); return { ...input,recordedAt:at }; });
  }
  getEntity(id: string): LineageEntity | null { const row=this.db.prepare("SELECT * FROM lineage_entities WHERE id=?").get(id) as Record<string,unknown>|undefined; return row ? this.entity(row) : null; }
  addRelation(input: Omit<LineageRelation,"id"|"recordedAt">): LineageRelation {
    assertId(input.fromId,"relation fromId"); assertId(input.toId,"relation toId"); if (input.activityId) assertId(input.activityId,"relation activityId"); const id=`lineage:sha256:${digest({ ...input,activityId:input.activityId ?? null })}`;
    return this.transaction(()=>{ if (!this.getEntity(input.fromId)||!this.getEntity(input.toId)) throw new Error("lineage relation endpoints must be recorded first"); const existing=this.db.prepare("SELECT * FROM lineage_relations WHERE id=?").get(id) as Record<string,unknown>|undefined; if (existing) return { id,fromId:String(existing.from_id),toId:String(existing.to_id),relation:existing.relation as LineageRelation["relation"],...(existing.activity_id ? { activityId:String(existing.activity_id) } : {}),recordedAt:Number(existing.recorded) }; const at=this.now(); this.db.prepare("INSERT INTO lineage_relations VALUES (?,?,?,?,?,?)").run(id,input.fromId,input.toId,input.relation,input.activityId ?? null,at); return { id,...input,recordedAt:at }; });
  }
  relationsFor(id: string): LineageRelation[] { return this.db.prepare("SELECT * FROM lineage_relations WHERE from_id=? OR to_id=? ORDER BY recorded,id").all(id,id).map((row)=>({ id:String(row.id),fromId:String(row.from_id),toId:String(row.to_id),relation:row.relation as LineageRelation["relation"],...(row.activity_id ? { activityId:String(row.activity_id) } : {}),recordedAt:Number(row.recorded) })); }
  createDatasetManifest(input: DatasetManifestInput): DatasetManifest {
    assertHash(input.byteSha256,"dataset byteSha256"); if (!input.schemaVersion||!input.license.trim()||!input.intendedRole.trim()) throw new Error("dataset manifest requires schemaVersion, license, and intendedRole"); if (!input.rowIds.length) throw new Error("dataset manifest requires ordered rowIds"); noDuplicate(input.rowIds,String,"dataset rowIds"); input.sourceArtifactIds.forEach((id)=>assertId(id,"dataset source artifact id"));
    const id=`dataset:sha256:${digest({ ...input,sourceArtifactIds:[...input.sourceArtifactIds],rowIds:[...input.rowIds] })}` as const;
    const current=this.db.prepare("SELECT body,recorded FROM dataset_manifests WHERE id=?").get(id) as { body:string;recorded:number }|undefined;
    if (current) return { ...json(current.body,{}) as Omit<DatasetManifest,"recordedAt">,recordedAt:Number(current.recorded) };
    for (const sourceId of input.sourceArtifactIds) if (!this.getEntity(sourceId)) throw new Error("dataset source artifact must be recorded first");
    const at=this.now(); const manifest:DatasetManifest={ ...input,id,rowCount:input.rowIds.length,recordedAt:at };
    this.recordEntity({ id,kind:"dataset",digest:input.byteSha256,metadata:{ schemaVersion:input.schemaVersion,license:input.license,intendedRole:input.intendedRole,rowCount:input.rowIds.length },retentionClass:"lineage" });
    return this.transaction(()=>{ this.db.prepare("INSERT INTO dataset_manifests VALUES (?,?,?)").run(id,JSON.stringify({ ...manifest,recordedAt:undefined }),at); for (const sourceId of input.sourceArtifactIds) { const relationId=`lineage:sha256:${digest({ fromId:id,toId:sourceId,relation:"derived_from",activityId:null })}`; this.db.prepare("INSERT INTO lineage_relations VALUES (?,?,?,?,?,?)").run(relationId,id,sourceId,"derived_from",null,at); } return manifest; });
  }
  getDatasetManifest(id: string): DatasetManifest | null { const row=this.db.prepare("SELECT body,recorded FROM dataset_manifests WHERE id=?").get(id) as { body:string;recorded:number }|undefined; return row ? { ...json(row.body,{}) as Omit<DatasetManifest,"recordedAt">,recordedAt:Number(row.recorded) } : null; }
  createSuite(input: EvaluationSuiteInput): EvaluationSuite {
    if (!input.name.trim()||!input.version.trim()||!input.license.trim()||!input.capabilityDomain.trim()||!input.cases.length) throw new Error("suite requires name, version, license, capability domain, and cases"); assertId(input.datasetId,"suite datasetId"); assertHash(input.datasetSha256,"suite datasetSha256"); if (!Number.isSafeInteger(input.repeats)||input.repeats<1||!input.seeds.length||input.seeds.some((seed)=>!Number.isSafeInteger(seed))) throw new Error("suite requires repeats and integer seeds");
    const cases=input.cases.map((item)=>{ assertHash(item.promptTemplateSha256,"case promptTemplateSha256"); if (!item.name.trim()||!item.datasetRevision.trim()) throw new Error("case name and datasetRevision are required"); const tags=[...(item.tags ?? [])].sort(); return { ...item,tags,id:`case:sha256:${digest({ ...item,tags })}` as const }; }); noDuplicate(cases,(item)=>item.id,"suite cases"); const suiteInput={ ...input,cases }; const id=`suite:sha256:${digest(suiteInput)}` as const;
    return this.transaction(()=>{ const existing=this.db.prepare("SELECT * FROM evaluation_suites WHERE id=?").get(id) as Record<string,unknown>|undefined; if (existing) return this.suite(existing); const at=this.now(); const suite:EvaluationSuite={ ...suiteInput,id,createdAt:at }; this.db.prepare("INSERT INTO evaluation_suites VALUES (?,?,?)").run(id,JSON.stringify({ ...suite,createdAt:undefined }),at); for (const item of cases) this.db.prepare("INSERT INTO evaluation_cases VALUES (?,?,?)").run(id,item.id,JSON.stringify(item)); return suite; });
  }
  getSuite(id: string): EvaluationSuite | null { const row=this.db.prepare("SELECT * FROM evaluation_suites WHERE id=?").get(id) as Record<string,unknown>|undefined; return row ? this.suite(row) : null; }
  listSuites(): EvaluationSuite[] { return this.db.prepare("SELECT * FROM evaluation_suites ORDER BY created DESC,id").all().map((row)=>this.suite(row)); }
  startRun(input: EvaluationRunInput): EvaluationRun {
    assertId(input.id,"evaluation run id"); assertId(input.suiteId,"evaluation suiteId"); assertId(input.artifactId,"evaluation artifactId"); assertId(input.runtimeId,"evaluation runtimeId"); assertHash(input.chatTemplateSha256,"chatTemplateSha256"); assertHash(input.hostFingerprintSha256,"hostFingerprintSha256"); if (!input.softwareRevision.trim()||!input.environmentRevision.trim()||!Number.isSafeInteger(input.seed)||!Number.isSafeInteger(input.repeat)||input.repeat<1) throw new Error("evaluation run evidence is incomplete");
    return this.transaction(()=>{ if (!this.getSuite(input.suiteId)) throw new Error("evaluation suite is not recorded"); const existing=this.db.prepare("SELECT * FROM evaluation_runs WHERE id=?").get(input.id) as Record<string,unknown>|undefined; if (existing) { const run=this.run(existing); if (canonical(runInputFrom(run))!==canonical(input)) throw new Error(`immutable evaluation run conflict: ${input.id}`); return run; } const at=this.now(); this.db.prepare("INSERT INTO evaluation_runs VALUES (?,?,?,?,?,?,?)").run(input.id,input.suiteId,JSON.stringify(input),"running",at,null,null); return { ...input,protocolVersion:LINEAGE_EVALUATION_SCHEMA_VERSION,state:"running",startedAt:at,results:[] }; });
  }
  finishRun(id: string, results: EvaluationCaseResult[]): EvaluationRun {
    return this.transaction(()=>{ const row=this.db.prepare("SELECT * FROM evaluation_runs WHERE id=?").get(id) as Record<string,unknown>|undefined; if (!row||row.state!=="running") throw new Error("only running evaluation runs can finish"); const runInput=json(String(row.body),{}) as EvaluationRunInput,suite=this.getSuite(runInput.suiteId); if (!suite) throw new Error("evaluation suite is not recorded"); noDuplicate(results,(result)=>result.caseId,"evaluation results"); const expected=suite.cases.map((item)=>item.id as string).sort(),received=[...results.map((item)=>item.caseId)].sort(); if (canonical(expected)!==canonical(received)) throw new Error("evaluation results must cover every immutable suite case exactly once"); for (const result of results) { if (!expected.includes(result.caseId)||!["pass","fail","error"].includes(result.outcome)||typeof result.rawOutput!=="string") throw new Error("invalid evaluation case result"); if (result.outcome==="error"&&!result.error) throw new Error("error results require structured error evidence"); if (result.metrics&&Object.values(result.metrics).some((value)=>!Number.isFinite(value))) throw new Error("result metrics must be finite numbers"); } const at=this.now(); for (const result of results) this.db.prepare("INSERT INTO evaluation_results VALUES (?,?,?)").run(id,result.caseId,JSON.stringify(result)); this.db.prepare("UPDATE evaluation_runs SET state='completed',completed=? WHERE id=?").run(at,id); return this.run(this.db.prepare("SELECT * FROM evaluation_runs WHERE id=?").get(id) as Record<string,unknown>); });
  }
  failRun(id: string,error: { code:string;message:string }): EvaluationRun { if (!error.code||!error.message) throw new Error("evaluation failure must be structured"); return this.transaction(()=>{ const row=this.db.prepare("SELECT * FROM evaluation_runs WHERE id=?").get(id) as Record<string,unknown>|undefined; if (!row||row.state!=="running") throw new Error("only running evaluation runs can fail"); const at=this.now(); this.db.prepare("UPDATE evaluation_runs SET state='failed',completed=?,error=? WHERE id=?").run(at,JSON.stringify(error),id); return this.run(this.db.prepare("SELECT * FROM evaluation_runs WHERE id=?").get(id) as Record<string,unknown>); }); }
  getRun(id: string): EvaluationRun | null { const row=this.db.prepare("SELECT * FROM evaluation_runs WHERE id=?").get(id) as Record<string,unknown>|undefined; return row ? this.run(row) : null; }
  compareRuns(ids: string[]): RunComparison { noDuplicate(ids,String,"run ids"); const runs=ids.map((id)=>this.getRun(id)).filter((run):run is EvaluationRun=>!!run),caseOutcomes:RunComparison["caseOutcomes"]={}; for (const run of runs) for (const result of run.results) (caseOutcomes[result.caseId] ??= {})[run.id]=result.outcome; return { runs:runs.map((run)=>({ id:run.id,suiteId:run.suiteId,artifactId:run.artifactId,runtimeId:run.runtimeId,state:run.state,...(run.summary ? { summary:run.summary } : {}) })),caseOutcomes }; }
}
type GlobalLineage = typeof globalThis & { __lal_lineage_evaluations?: LineageEvaluationRepository };
export function getLineageEvaluationRepository(): LineageEvaluationRepository { const global=globalThis as GlobalLineage; if (!global.__lal_lineage_evaluations) { const directories=ensurePlatformDirectories(resolvePlatformDirectories()); global.__lal_lineage_evaluations=new LineageEvaluationRepository({ databasePath:path.join(directories.state,"lineage-evaluations.sqlite") }); } return global.__lal_lineage_evaluations; }
