import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { resolveModelAcquisition, VerifiedModelImportStore, type OfflineCatalog } from "./model-acquisition.ts";

const bytes = Buffer.from("verified-model-fixture");
const catalog = (availability: "available" | "offline" = "available"): OfflineCatalog => ({ protocolVersion: 1, generatedAt: "2026-07-19T00:00:00.000Z", providers: { huggingface: availability, ollama: "unconfigured" }, models: [{ provider: "huggingface", id: "lal/demo-gguf", revision: "main", displayName: "LAL Demo", license: { spdx: "Apache-2.0", name: "Apache 2.0", requiresAcceptance: true, redistributable: true }, parameterCountBillion: 1, capabilities: ["chat"], files: [{ path: "demo.gguf", sizeBytes: bytes.length, sha256: crypto.createHash("sha256").update(bytes).digest("hex") }] }] });
const host = { availableDiskBytes: 1_000_000_000, availableRamBytes: 1_000_000_000, availableVramBytes: 1_000_000_000 };
test("offline provider metadata visibly degrades without a network fallback", () => { const result = resolveModelAcquisition(catalog("offline"), { provider: "huggingface", id: "lal/demo-gguf", acceptedLicense: true }, host); assert.deepEqual(result, { state: "unavailable", reason: "offline", detail: "huggingface metadata is offline; no network fallback is attempted" }); });
test("resolution plans bind license, file digest, and hardware estimates", () => { assert.equal(resolveModelAcquisition(catalog(), { provider: "huggingface", id: "lal/demo-gguf" }, host).state, "unavailable"); const result = resolveModelAcquisition(catalog(), { provider: "huggingface", id: "lal/demo-gguf", acceptedLicense: true }, host); assert.equal(result.state, "ready"); if (result.state !== "ready") return; assert.match(result.plan.id, /^acquisition-plan:sha256:[a-f0-9]{64}$/); assert.equal(result.plan.file.sha256, crypto.createHash("sha256").update(bytes).digest("hex")); const noDisk = resolveModelAcquisition(catalog(), { provider: "huggingface", id: "lal/demo-gguf", acceptedLicense: true }, { ...host, availableDiskBytes: 1 }); assert.equal(noDisk.state, "unavailable"); if (noDisk.state === "unavailable") assert.equal(noDisk.reason, "insufficient_disk"); });
test("staged imports verify exact bytes, bound size, and delete partials on cancellation", (t) => { const root = fs.mkdtempSync(path.join(os.tmpdir(), "lal-import-")); t.after(() => fs.rmSync(root, { recursive: true, force: true })); const ready = resolveModelAcquisition(catalog(), { provider: "huggingface", id: "lal/demo-gguf", acceptedLicense: true }, host); assert.equal(ready.state, "ready"); if (ready.state !== "ready") return; const store = new VerifiedModelImportStore(root); store.begin("demo", ready.plan, host.availableDiskBytes); store.append("demo", bytes.subarray(0, 5)); store.append("demo", bytes.subarray(5)); const completed = store.verify("demo"); assert.equal(completed.state, "verified"); assert.equal(fs.readFileSync(completed.artifactPath!, "utf8"), bytes.toString()); store.begin("cancel", ready.plan, host.availableDiskBytes); store.append("cancel", bytes.subarray(0, 3)); store.requestCancel("cancel"); assert.equal(store.settleCancel("cancel").state, "cancelled"); });
test("digest mismatch is a failed import, never an activated artifact", (t) => { const root = fs.mkdtempSync(path.join(os.tmpdir(), "lal-import-")); t.after(() => fs.rmSync(root, { recursive: true, force: true })); const ready = resolveModelAcquisition(catalog(), { provider: "huggingface", id: "lal/demo-gguf", acceptedLicense: true }, host); assert.equal(ready.state, "ready"); if (ready.state !== "ready") return; const store = new VerifiedModelImportStore(root); store.begin("bad", ready.plan, host.availableDiskBytes); store.append("bad", Buffer.alloc(bytes.length, 4)); assert.equal(store.verify("bad").state, "failed"); });
